/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_steepout_fsm_FileSystemInfo */

#ifndef _Included_net_steepout_fsm_FileSystemInfo
#define _Included_net_steepout_fsm_FileSystemInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _get_fs_info
 * Signature: (I)Lnet/steepout/fsm/FileSystemDesc;
 */
JNIEXPORT jobject JNICALL Java_net_steepout_fsm_FileSystemInfo__1get_1fs_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _native_open
 * Signature: (Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1native_1open
  (JNIEnv *, jclass, jstring, jshort);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _native_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1native_1close
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _native_read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1native_1read
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _native_write
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1native_1write
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _native_lseek
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1native_1lseek
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     net_steepout_fsm_FileSystemInfo
 * Method:    _fcntl_basic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_steepout_fsm_FileSystemInfo__1fcntl_1basic
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
